### PR TITLE
Ticks

### PR DESCRIPTION
**Pull request by spencer516**
Ahhh...looks like I branched off of that "tests passing branch". 

Anyway, started creating a way to create ticks. See localhost:4200/bubble-1

### CODE REVIEW

**Comment by spencer516** [comment]
@bdvholmes — There's a working version of the NY Times viz with support for the team selector. Visit: `http://localhost:4200/nytimes-strikeouts`. Not sure why I put that in this branch...except to say that it's an impetus to get the axes in there. ;-) 

It took me about 20 minutes once I got the data all setup to build what's there now. I think that's a good sign. 

Now...this brought forward a...\*ahem\*...critical problem which you'll notice once you render the page. Because Ember wants to instantiate all these components and put something in the DOM, it takes *forever* for it to build all of those objects. I think this is where we probably need to solicit some advice from the outer community as we don't really *need* those components...but we do want them to be as component like as we can be....hmmmm....

**Comment by spencer516** [comment]
screen shot 2015-08-27 at 5 55 05 pm

**Comment by bdvholmes** [comment]
WOOHOO! Dare I say it but could this be the day for the fabled `GlimmerComponent`. They don't have outside elements right?

**Comment by bdvholmes** [comment]
Tres sexy. Also I have a present for you.

**Comment by spencer516** [comment]
It's become quad-sexy. (That's after `tres` sexy, ya?) 

I've added in some of the axes stuff. 'Tis getting closer: 
screen shot 2015-08-31 at 6 01 20 pm

**Comment by spencer516** [comment]
Merging, though we still need to address some of the performance issues on the NY Times example (also, I'd built it to serve the data from an HTTP-Mock...should probably mock this data).

**Comment by bdvholmes** [comment]
:tada:

**Pull request merged**
